# Use a Windows Server Core base image
FROM mcr.microsoft.com/windows/servercore:ltsc2022

# Arguments for versions
ARG COMPILER_VERSION="2022"
ARG CMAKE_VERSION="3.29.5"

# Set shell to PowerShell
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Download and install CMake
RUN Invoke-WebRequest -Uri "https://github.com/Kitware/CMake/releases/download/v$env:CMAKE_VERSION/cmake-$env:CMAKE_VERSION-windows-x86_64.msi" -OutFile cmake.msi; \
    Start-Process -FilePath msiexec.exe -ArgumentList "/i", "cmake.msi", "/quiet", "/qn", "/norestart" -NoNewWindow -Wait; \
    Remove-Item cmake.msi

# Verify that ctest is available
RUN ctest --version

# Add CMake to the system PATH
RUN $env:PATH = 'C:\Program Files\CMake\bin;' + $env:PATH; \
    [Environment]::SetEnvironmentVariable('PATH', $env:PATH, [EnvironmentVariableTarget]::Machine)

# Download and install Git
RUN Invoke-WebRequest -Uri "https://github.com/git-for-windows/git/releases/download/v2.38.1.windows.1/Git-2.38.1-64-bit.exe" -OutFile git-installer.exe; \
    Start-Process -FilePath .\git-installer.exe -ArgumentList "/VERYSILENT", "/NORESTART", "/NOCANCEL", "/SP-", "/CLOSEAPPLICATIONS", "/RESTARTAPPLICATIONS", "/COMPONENTS=icons,ext\reg\shellhere,assoc,assoc_sh" -NoNewWindow -Wait; \
    Remove-Item git-installer.exe

# Download and install VS Build Tools
RUN Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_buildtools.exe" -OutFile vs_buildtools.exe; \
    Start-Process -FilePath .\vs_buildtools.exe -ArgumentList \
    "--quiet", "--wait", "--norestart", "--nocache", \
    "--installPath", "C:\BuildTools", \
    "--add", "Microsoft.VisualStudio.Component.VC.Tools.x86.x64" \
    -NoNewWindow -Wait; \
    Remove-Item .\vs_buildtools.exe -Force

# Download and install Intel oneAPI Base Toolkit (includes MKL)
RUN Invoke-WebRequest -Uri "https://registrationcenter-download.intel.com/akdlm/IRC_NAS/e83a8e64-04fc-45df-85c6-c2208d03bdb5/w_BaseKit_p_2024.2.0.635_offline.exe" -OutFile "w_BaseKit_p_2024.2.0.635_offline.exe"; \
    Start-Process -FilePath "w_BaseKit_p_2024.2.0.635_offline.exe" -ArgumentList "-s -a --silent --eula accept --components intel.oneapi.win.mkl.devel" -Wait; \
    Remove-Item "w_BaseKit_p_2024.2.0.635_offline.exe"

# Download and install Intel Fortran Compiler
RUN Invoke-WebRequest -Uri "https://registrationcenter-download.intel.com/akdlm/IRC_NAS/0d500705-397e-41b3-8b2b-2a3da1753fc2/w_HPCKit_p_2024.2.0.633_offline.exe" -OutFile "w_HPCKit_p_2024.2.0.633_offline.exe"; \
    Start-Process -FilePath "w_HPCKit_p_2024.2.0.633_offline.exe" -ArgumentList "-s -a --silent --eula accept --components intel.oneapi.win.ifort-compiler" -Wait; \
    Remove-Item "w_HPCKit_p_2024.2.0.633_offline.exe"

# Set the entry point to PowerShell
ENTRYPOINT ["powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass"]