name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [gcc, clang, msvc]
        blas: [NONE]
        include:
          - compiler: gcc
            cc: gcc-12
            cxx: g++-12
          - compiler: clang
            cc: clang-18
            cxx: clang++-18
        exclude:
          - os: windows-latest
            compiler: gcc
          - os: ubuntu-latest
            compiler: msvc
          - os: windows-latest
            blas: MKL
          - os: windows-latest
            blas: OpenBLAS

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build
        if [ "${{ matrix.compiler }}" = "gcc" ]; then
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y gcc-12 g++-12
        elif [ "${{ matrix.compiler }}" = "clang" ]; then
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          sudo apt-get install -y clang-tidy-18 clang-format-18
        fi
        if [ "${{ matrix.blas }}" = "OpenBLAS" ]; then
          sudo apt-get install -y gfortran
        elif [ "${{ matrix.blas }}" = "MKL" ]; then
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update
          sudo apt-get install -y intel-oneapi-mkl-devel intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic
        fi

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install cmake ninja
        if ("${{ matrix.compiler }}" -eq "clang") {
          choco install llvm
        }

    - name: Check Clang-Format
      if: matrix.compiler == 'clang' && runner.os == 'Linux'
      run: |
        find include/squint -iname '*.hpp' -o -iname '*.cpp' | xargs clang-format-18 -i
        git diff --exit-code
      shell: bash

    - name: Configure CMake
      run: |
        if [ "${{ runner.os }}" = "Linux" ]; then
          export CC=${{ matrix.cc }}
          export CXX=${{ matrix.cxx }}
        elif [ "${{ runner.os }}" = "Windows" ]; then
          if [ "${{ matrix.compiler }}" = "clang" ]; then
            export CC=clang
            export CXX=clang++
          fi
        fi
        
        if [ "${{ matrix.blas }}" = "MKL" ] && [ "${{ runner.os }}" = "Linux" ]; then
          source /opt/intel/oneapi/setvars.sh
        fi
        
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DSQUINT_BUILD_DOCUMENTATION=OFF -DSQUINT_BLAS_BACKEND=${{ matrix.blas }}
      shell: bash

    - name: Build
      run: cmake --build build
      
    - name: Test
      working-directory: build
      run: ctest --output-on-failure

    - name: Run Clang-Tidy
      if: matrix.compiler == 'clang' && runner.os == 'Linux'
      run: |
        find ./include/squint -name '*.cpp' -or -name '*.hpp' | \
        xargs -P $(nproc) clang-tidy-18 -p build > clang_tidy_output.txt
        if [ -s clang_tidy_output.txt ]; then
          echo "Clang-Tidy found issues:"
          cat clang_tidy_output.txt
          exit 1
        else
          echo "Clang-Tidy passed without issues."
        fi
      shell: bash