name: SQUINT CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++-12, clang++-15, clang++-16, clang++-17, clang++-18]

    steps:
    - uses: actions/checkout@v4

    - name: Install compiler and libraries
      run: |
        sudo apt-get update
        if [[ "${{ matrix.compiler }}" == clang++* ]]; then
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          CLANG_VERSION=$(echo "${{ matrix.compiler }}" | sed 's/clang++-//')
          sudo ./llvm.sh $CLANG_VERSION
          sudo apt-get install -y clang-$CLANG_VERSION libc++-$CLANG_VERSION-dev libc++abi-$CLANG_VERSION-dev lld-$CLANG_VERSION
        else
          sudo apt-get install -y ${{ matrix.compiler }}
        fi

    - name: Configure CMake
      env:
        CXX: ${{ matrix.compiler }}
      run: |
        if [[ "${{ matrix.compiler }}" == clang++* ]]; then
          CLANG_VERSION=$(echo "${{ matrix.compiler }}" | sed 's/clang++-//')
          export CXXFLAGS="-stdlib=libc++"
          export LDFLAGS="-stdlib=libc++ -fuse-ld=lld-$CLANG_VERSION"
          cmake -B ${{github.workspace}}/build -DSQUINT_BUILD_TESTS=ON -DCMAKE_CXX_FLAGS="$CXXFLAGS" -DCMAKE_EXE_LINKER_FLAGS="$LDFLAGS" -DCMAKE_SHARED_LINKER_FLAGS="$LDFLAGS"
        else
          cmake -B ${{github.workspace}}/build -DSQUINT_BUILD_TESTS=ON
        fi

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure

  build-and-test-windows:
    name: Build and Test (Windows)
    runs-on: windows-latest
    strategy:
      matrix:
        clang_version: [15, 16, 17, 18]

    steps:
    - uses: actions/checkout@v4

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: ${{ matrix.clang_version }}

    - name: Configure CMake
      env:
        CXX: clang++
      run: |
        cmake -B ${{github.workspace}}/build -DSQUINT_BUILD_TESTS=ON -DCMAKE_CXX_FLAGS="/EHsc" -T ClangCL

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C Release --output-on-failure

  clang-tidy:
    name: Clang-Tidy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Clang and Clang-Tidy
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tidy

    - name: Run Clang-Tidy
      run: |
        find include -name '*.cpp' -or -name '*.hpp' | \
        xargs clang-tidy -p build \
        --config-file=.clang-tidy

    - name: Check Clang-Tidy result
      run: |
        if [ $? -ne 0 ]; then
          echo "Clang-Tidy found issues. Please fix them before merging."
          exit 1
        fi